### ISSUE TITLE
How to use .pyd file in latest version(3.4.0)?

### ISSUE THREAD

**Issue by GentlerMan** [IronLanguages/ironpython3#1207] opened 2021-05-06 07:06 UTC
### Prerequisites

The issue tracker is used to report bugs and request new features, NOT to ask questions.

Questions should be posted to the users mailing list which can be accessed at 
https://ironpython.groups.io/g/users. 

* [ *] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
* [ ] Did you perform a cursory search?

### Description

I am not sure the pyd lib file can be used in 3.4.0, If so, so much the better

**Comment by slozier** [comment] 2021-05-06 13:25
Duplicate of https://github.com/IronLanguages/ironpython3/issues/78. Unfortunately pyd files are DLLs that require the CPython API so they won't work with IronPython.

**Closed by slozier** 2021-05-06 13:25 UTC
