### ISSUE TITLE
map() fails on Array[str]

### ISSUE THREAD

**Issue by Mt-SQ** [IronLanguages/ironpython3#1666] opened 2023-03-08 02:20 UTC
### Description
List[str] works but Array[str] fails.
```
IronPython 3.4.0 (3.4.0.1000)
[.NETFramework,Version=v4.6.2 on .NET Framework 4.8.9139.0 (64-bit)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from System.Collections.Generic import List
>>> list(map(str, List[int]([1, 3, 5, 7, 9])))
['1', '3', '5', '7', '9']
>>> list(map(int, List[str](['1', '3', '5', '7', '9'])))
[1, 3, 5, 7, 9]
>>> from System import Array
>>> list(map(str, Array[int]([1, 3, 5, 7, 9])))
['1', '3', '5', '7', '9']
>>> list(map(int, Array[str](['1', '3', '5', '7', '9'])))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: int() takes at most 3 arguments (6 given)
```
IronPython 2.7 works as expected.
```
IronPython 2.7.12 (2.7.12.1000)
[.NETFramework,Version=v4.5 on .NET Framework 4.8.9139.0 (64-bit)]
Type "help", "copyright", "credits" or "license" for more information.
>>> from System import Array
>>> list(map(str, Array[int]([1, 3, 5, 7, 9])))
['1', '3', '5', '7', '9']
>>> list(map(int, Array[str](['1', '3', '5', '7', '9'])))
[1, 3, 5, 7, 9]
```

**Comment by slozier** [comment] 2023-03-10 00:24
Thanks for the report! Looks like it's binding the `Array[str]` argument directly to the `params object[]`. There are probably other places that have the same issue (e.g. `zip`).

**Comment by Mt-SQ** [comment] 2023-03-10 01:39
Thank you for your confirmation.
I will add the verification results.
```
IronPython 3.4.0 (3.4.0.1000)
[.NETFramework,Version=v4.6.2 on .NET Framework 4.8.9139.0 (64-bit)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from System import Array, Char
>>> list(zip(range(5), Array[str](['1', '3', '5', '7', '9'])))
[(0, '1'), (1, '3'), (2, '5'), (3, '7'), (4, '9')]
>>> list(filter(lambda s: int(s) <= 5, Array[str](['1', '3', '5', '7', '9'])))
['1', '3', '5']
>>> list(map(int.Parse, Array[Char](['1', '3', '5', '7', '9'])))
[1, 3, 5, 7, 9]
>>> list(map(int.Parse, Array[str](['1', '3', '5', '7', '9'])))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Parse() takes at most 3 arguments (5 given)
```

**Comment by slozier** [comment] 2023-06-23 19:51
Going to close this since it looks like the same issue as https://github.com/IronLanguages/ironpython3/issues/892. As for reproducing with zip:
```py
data = ['1','2','3','4']
assert list(zip(System.Array[System.String](data))) == list(zip(data))
```

**Closed by slozier** 2023-06-23 19:51 UTC
Labels: bug, regression, confirmed
