### ISSUE TITLE
IronPython doesn't run on net5.0-windows

### ISSUE THREAD

**Issue by spasarto** [IronLanguages/ironpython3#1243] opened 2021-06-23 01:33 UTC
### Prerequisites

The issue tracker is used to report bugs and request new features, NOT to ask questions.

Questions should be posted to the users mailing list which can be accessed at 
https://ironpython.groups.io/g/users. 

* [x ] Are you running the latest version?
* [x ] Are you reporting to the correct repository?
* [x ] Did you perform a cursory search?

### Description

Application does not run with net5-windows framework target.

The problem lies in the nuget package target for net5-windows only contains IronPython.WPF.dll. It should also include IronPython.dll, IronPython.Modules.dll, etc. Deleting the net5-windows target from the nuget package, adding it to your local feed, and updating to the local version will fix the problem stated above.

### Steps to Reproduce

1. Create a new csproj with TargetFramework net5.0-windows or net5.0-windows10.0.17763.0.
2. Add a PackageReference to IronPython 3.4.0-alpha1
3. Add print('hello world') example code in Program.cs
4. Run application

**Expected behavior:** Application prints hello world and completes successfully

**Actual behavior:** Runtime error: Cannot find IronPython version 3.4.0.

### Versions 

You can get this information from executing `ipy -V`.

IronPython 3.4.0-alpha1

**Comment by slozier** [comment] 2021-06-23 14:10
Thanks for the report, this is a duplicate of https://github.com/IronLanguages/ironpython3/issues/1227

**Closed** 2022-03-23 23:44 UTC
